#!/bin/bash

MPORT=`relation-get port`
MHOST=`relation-get private-address`

if [ -z "$MPORT" ] ; then
	juju-log "We don't 'actually' have a connection yet"
    exit 0
fi

juju-log "Looks like memcache is on $MPORT at $MHOST"

sed -i  -e "s/^session.save_path = .*//" \
		-e "s@^session.save_handler = .*@session.save_handler = memcache\nsession.save_path=\"tcp://$MHOST:$MPORT?persistent=1&weight=1&timeout=1&retry_interval=15\"@" \
		/etc/php5/fpm/php.ini

service php5-fpm restart
service nginx restart
