#!/bin/bash

set -eu

juju-log "We've got a db"
hostname=`unit-get public-address`
private_name=`hostname -f`
juju-log "Retrieved hostname: $hostname"

# Check we haven't already been setup.
wp_install_path="/var/www/omgubuntu.co.uk"
config_file_path="$wp_install_path/wp-config.php"

if [ -f "$config_file_path" ]; then
	juju-log "OMG Ubuntu is already setup, just silently going away"
	exit 0
fi

database=`relation-get database`
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`

if [ -z "$database" ] ; then
    exit 0
fi

secret_key=`pwgen 10 1`
source "/usr/share/charm-helper/sh/net.sh"

##
# OH COME ON WORDPRESS.ORG NO VALID SSL CERTIFICATE?
# Psh, whatever, plain-text for now. #blamenacin
# https://twitter.com/#!/marcoceppi/status/181570187655520260
LATEST_WORDPRESS="http://wordpress.org/latest.tar.gz"
DOWNLOAD=`ch_get_file "$LATEST_WORDPRESS" "http://wordpress.org/latest.tar.gz.sha1"`
##

if [ ! -f "$DOWNLOAD" ] || [ -z "$DOWNLOAD" ]; then
	juju-log "Failed to retrieve $LATEST_WORDPRESS"
	exit 1
fi

juju-log "Extract ALL THE FILES"
tar -xzf $DOWNLOAD

mkdir -p $wp_install_path

juju-log "Move them in to place, but just 'drop' them in place."
rsync -az wordpress/ $wp_install_path

juju-log "Clean up"
rm -rf wordpress

if [ -f /etc/default/s3cmd ] ; then
	juju-log "Check if we've actually created this Database before"
	CUR_TABLE_COUNT=`mysql -h $host -u $user -p$password -Nse "SELECT count(TABLE_NAME) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=\"$database\""`
	if [ $CUR_TABLE_COUNT -eq 0 ]; then
		juju-log "Get the last database dump"
		mkdir -p /mnt/restore/
		LATEST=`s3cmd -c /etc/default/s3cmd ls s3://omgubuntu.co.uk/backups/ | tail -n 1 | awk '{ print $4 }'`
		juju-log "$LATEST dump"
		s3cmd -c /etc/default/s3cmd get $LATEST /mnt/restore/

		juju-log "Extracting"
		tar -xzf /mnt/restore/$(basename $LATEST)

		juju-log "Pushing in to MySQL"
		mysql -h $host -u $user -p$password $database < *.sql
		rm -f *.sql
	else
		juju-log "I am a not unique, a database already exists"
	fi
else
    juju-log "No AWS Credentials, not restoring database from S3"
fi

juju-log "Dropping OMG specific files: Themes, plugins, etc in to position"
rsync -az files/wordpress/ $wp_install_path

juju-log "Writing wordpress config file $config_file_path"
# Write the wordpress config
cat > $config_file_path <<EOF
<?php
define('DB_NAME', '$database');
define('DB_USER', '$user');
define('DB_PASSWORD', '$password');
define('DB_HOST', '$host');
define('SECRET_KEY', '$secret_key');

define('WP_CACHE', true);

/*
define('AUTH_KEY', '$secret_key');
define('SECURE_AUTH_KEY', '$secret_key');
define('LOGGED_IN_KEY', '$secret_key');
define('NONCE_KEY', '$secret_key');
*/

\$table_prefix  = 'wp_';

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');

EOF
chmod 0644 $config_file_path

juju-log "Enabling apache site: $hostname"

chown -R www-data.www-data $wp_install_path

if [ ! -f /etc/cron.daily/omg-backup ]; then
	juju-log "Put the backup process in place"
	rsync -az files/omg-backup /etc/cron.daily/
	chmod 0755 /etc/cron.daily/omg-backup
fi

sed -i -e "s@DB_HOST=\".*\"@DB_HOST=\"$host\"@" \
    -e "s@DB_USER=\".*\"@DB_USER=\"$user\"@" \
    -e "s@DB_PASS=\".*\"@DB_PASS=\"$password\"@" \
    -e "s@DB_NAME=\".*\"@DB_NAME=\"$database\"@" \
    /etc/cron.daily/omg-backup

# Restart apache
juju-log "Restarting nginx service"
service nginx restart

# Make it publicly visible, once the wordpress service is exposed
open-port 80/tcp
