#!/bin/bash

set -eu

juju-log "We've got a db"

source inc/common

if [ -f "$config_file_path" ]; then
	# No longer to quietly in to that good night. Update the wp-config file with new DB values
	juju-log "WordPress is already setup, just silently going away"
	exit 0
fi

database=`relation-get database`
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`

if [ -z "$database" ] ; then
    exit 0
fi

secret_key=`pwgen 10 1`
echo $secret_key > wp_secret
source "/usr/share/charm-helper/sh/net.sh"

##
# OH COME ON WORDPRESS.ORG NO VALID SSL CERTIFICATE?
# Psh, whatever, plain-text for now. #blamenacin
# https://twitter.com/#!/marcoceppi/status/181570187655520260
# I was wrong, we need to use something other than WGET, like cURL
LATEST_WORDPRESS="http://wordpress.org/latest.tar.gz"
DOWNLOAD=`ch_get_file "$LATEST_WORDPRESS" "http://wordpress.org/latest.tar.gz.sha1"`
##

if [ ! -f "$DOWNLOAD" ] || [ -z "$DOWNLOAD" ]; then
	juju-log "Failed to retrieve $LATEST_WORDPRESS"
	exit 1
fi

juju-log "Extract ALL THE FILES"
tar -xzf $DOWNLOAD

mkdir -p $wp_install_path

juju-log "Move them in to place, but just 'drop' them in place."
rsync -az wordpress/ $wp_install_path

juju-log "Clean up"
rm -rf wordpress

juju-log "Dropping User specific files: Themes, plugins, etc in to position"
rsync -az files/wordpress/ $wp_install_path

juju-log "Writing wordpress config file $config_file_path"
# Write the wordpress config
cat > $config_info_path <<EOF
<?php
define('DB_NAME', '$database');
define('DB_USER', '$user');
define('DB_PASSWORD', '$password');
define('DB_HOST', '$host');
define('SECRET_KEY', '$secret_key');

define('WP_CACHE', true);

/*
define('AUTH_KEY', '$secret_key');
define('SECURE_AUTH_KEY', '$secret_key');
define('LOGGED_IN_KEY', '$secret_key');
define('NONCE_KEY', '$secret_key');
*/

\$table_prefix  = 'wp_';

EOF

cat > $config_file_path <<EOF
<?php

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');

/** Pull in the config information */
require_once(ABSPATH . 'wp-info.php');
include_once(ABSPATH . 'wp-overrides.php');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');

remove_filter('template_redirect', 'redirect_canonical');

EOF

chmod 0644 $config_file_path
touch /var/www/wp-overrides.php

juju-log "Enabling apache site: $hostname"

chown -R www-data.www-data $wp_install_path

# Restart nginx
juju-log "Restarting nginx service"
service nginx restart

# Make it publicly visible, once the wordpress service is exposed
open-port 80/tcp
