#!/bin/bash

DB_HOST=""
DB_USER=""
DB_PASS=""
DB_NAME=""
NOW=`date "+%Y%m%d-%H%M"`

cd /mnt

mysqldump -h $DB_HOST -u $DB_USER -p$DB_PASS $DB_NAME > mysql.$NOW.sql
tar -czf mysql.$NOW.sql.tar.gz mysql.$NOW.sql

s3cmd put mysql.$NOW.sql.tar.gz s3://omgubuntu.co.uk/backups/
